apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    ksonnet.io/managed: '{"pristine":"H4sIAAAAAAAA/5ySP2/cMAzF934MzrIdZzTQ4dCk26WHFihQBIcDraMvaiRRkGi1RaDvXuj+OBmSDNkoWfy9x0c/AQbzk2Iy7GEA+ivka5263I8k2IOCR+P3MMANBcv/HHkBBY4E9ygIwxN4dAQDyNT85rHhQBGFY5N7tOEBr0EdX6SAuj57nEeaLP+BoiAF0pUQKVijMcHQKxBywaJQ/fBSxuJINr0tCOUFUbMXNJ5iguG+Hp3DOsU9dByku5joZFr621ytNg3axJYPwkn2FGO9y5972Cogn4+0s/76127z7WZ3t1rf/tisvtyCgox2pq+RXfUwGbL77zQt9QblAYZlqPY5llKKeo37IWSlbRUYh4eKO+jYGl5Gbo73qQnzaI3uZNpdAhjyVXvdXp339UrACjLb2dGaZy+nYF0tzyY6Et1p9pM5PDNO5+bUCGVbnSWK2WhaaV27794XuyywYtYY3vnhztLlbe1Syqf/AAAA//8BAAD//xjMOOjyAgAA"}'
  creationTimestamp: 2019-03-22T01:51:41Z
  generation: 1
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
  name: tf-job-operator-v1alpha2
  namespace: kubeflow
  resourceVersion: "705"
  selfLink: /apis/extensions/v1beta1/namespaces/kubeflow/deployments/tf-job-operator-v1alpha2
  uid: 0a1b606b-4c45-11e9-aaee-0242ac11001b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: tf-job-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: tf-job-operator
    spec:
      containers:
      - command:
        - /opt/kubeflow/tf-operator.v2
        - --alsologtostderr
        - -v=1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: gcr.io/kubeflow-images-public/tf_operator:v0.2.0
        imagePullPolicy: IfNotPresent
        name: tf-job-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tf-job-operator
      serviceAccountName: tf-job-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: tf-job-operator-config
        name: config-volume
status:
  availableReplicas: 1
  conditions:
